# This workflow compiles the project and runs all tests.

name: SpinalCrypto Tests

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: |
          sbt compile

      - name: Install verilator
        run: |
          sudo apt install -y verilator

      - name: Run tests
        run: |
          sbt test
